### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by jp1017** [tinify/tinify-java#4]
Can this be used in Android Studio ?

**Comment by reutenauer** [comment]
Yes, there are other Android developers using the client.

**Comment by jp1017** [comment]
So, how can I get the jar? Compile this by myself?

I used this in AS, 
>compile 'com.tinify:tinify:1.0'

But I can't get this lib in Maven center

**Comment by jp1017** [comment]
I got this using the latest version `1.4.0`,:

>compile 'com.tinify:tinify:1.4.0'
