### ISSUE TITLE
is this possible for grails?

### ISSUE THREAD

**Issue by akiong** [tinify/tinify-java#5]
hi... as i know, is there has maven plugin then the plugin must available in grails.org

or is there any jar for us

thank you

**Comment by simonwahlstrom** [comment]
Hello! I'm not entirely sure what you are asking for. 

This is the only repository for the Java client (that we are the owners of).

**Comment by akiong** [comment]
yes, we are using java as a compiler to,  we are using gradle .

is there tinypny plugin for gradle?

like this one. [This plugin, available in maven also gradle](https://mvnrepository.com/artifact/org.codehaus.groovy.modules.http-builder/http-builder/0.6#gradle-a)

**Comment by warflower** [comment]
You can find the plugin on Maven: http://search.maven.org/#search|ga|1|tinify

If you click on the version you will see more information as well as instructions on how to include the plugin in Gradle/Grails.

**Comment by akiong** [comment]
oh i see,, you are right..thank you

**Comment by warflower** [comment]
You're welcome!
