### ISSUE TITLE
Do you have an off-line version of Android?

### ISSUE THREAD

**Issue by Sabirjan** [tinify/tinify-java#8]
Do you have an off-line version of Android?
The client network is slow and can't upload large pictures.

**Comment by emielvanlankveld** [comment]
Hi Sabirjan,

Thank you for reaching out. Unfortunately at this time we do not offer an offline version of our compression service. 

Would it be an option for you to explore the images compressing in the background at a later time after uploading so it doesn't break the flow of the user?

**Comment by Sabirjan** [comment]
Thank you for your reply.
I'm in Urumqi, Xinjiang.
We're asking for your URL, a bit slow.
We are required to complete compression within 1-2 seconds. The time is too long and the experience is not good.
I've been looking for something else for the time being. Thank you
